introduce upgrading capability

diff --git a/packages/sx05re/emuelec/bin/batocera/emuelec-upgrade b/packages/sx05re/emuelec/bin/batocera/emuelec-upgrade
--- a/packages/sx05re/emuelec/bin/batocera/emuelec-upgrade
+++ b/packages/sx05re/emuelec/bin/batocera/emuelec-upgrade
@@ -1,91 +1,30 @@
 #!/bin/bash
 
-do_clean() {
-    test -n "${GETPERPID}" && kill -9 "${GETPERPID}"
-     rm -f "/storage/.update/*"
- }
-trap do_clean EXIT
+update_directory=/storage/roms/retroverse-os-patches
 
-getPer() {
-    TARVAL=$1
-  
-    while true
-    do
-    touch "/storage/.update/${UFILE}"
-	CURVAL=$(stat "/storage/.update/${UFILE}" | grep -E '^[ ]*Size:' | sed -e s+'^[ ]*Size: \([0-9][0-9]*\) .*$'+'\1'+)
-	CURVAL=$((${CURVAL} / 1024 / 1024))
-	PER=$((${CURVAL}*100/${TARVAL}))
-	echo "downloading >>> ${PER}%"
-	sleep 5
-    done
-}
-
-if [ "$1" == "canupdate" ]; then
-available=$(updatecheck.sh canupdate)
-	echo "$available"
-	if [[ "$available" == "no" ]]; then
-		exit 12
-	else
-		exit 0
-	fi
+if [ ! -d "$update_directory" ]; then
+  echo "patches directory not found"
+  exit 1
 fi
 
-#Started from Terminal/SSH or from Emulationstation?
-[ -t 1 ] && TERMINAL=1 || TERMINAL=0
+# go to the retroverse directory, this should be a fixed path
+cd $update_directory
 
-echo "starting the upgrade..."
+# pull latest changes from the repository
+git pull
 
-# download directory
-mkdir -p /storage/.update || exit 1
+# cp and overwrite all pulled files into the retroverse system
+rsync -a --exclude '.git' ./* /
 
-# get size to download
-url=$(updatecheck.sh geturl)
-UFILE=${url##*/}
-echo "url: ${url}"
-size=$(updatecheck.sh getsize)
-size=$((size / 1024 / 1024))
-echo "need to download ${size}mB"
+# apply patches if any
+chmod 755 -R /storage/.config/emuelec/scripts/
+for file in /storage/.config/emuelec/scripts/patches/*; do
+  echo "applying patch $file"
+  "$file"
+done
 
-# check free space on fs
-    freespace=$(df -m "/storage/.update/" | tail -1 | awk '{print $4}')
-    test $? -eq 0 || exit 1
-if test "${size}" -gt "${freespace}"; then
-	echo "Not enough space on ${fs} to download the update"
-	exit 1
-fi
+# write the current version
+current_version=$(git rev-list --count HEAD)
+echo "1.0$current_version" >/storage/.config/EE_VERSION
 
-
-# download
-if [ $TERMINAL = 0 ]; then
-    # Download by EMULATIONSTATION
-    getPer "${size}" &
-    GETPERPID=$!
-    curl -sfL "${url}" -o "/storage/.update/${UFILE}" || exit 1
-    kill -9 "${GETPERPID}"
-    GETPERPID=
-else
-    # Download inside SSH/TERMINAL
-    wget -q "${url}" -O "/storage/.update/${UFILE}" || exit 1
-fi
-
-# try to download an sha256 checksum
-curl -sfL "${url}.sha256" -o "/storage/.update/${UFILE}.sha256"
-if test -e "/storage/.update/${UFILE}.sha256"
-then
-    DISTMD5=$(cat "/storage/.update/${UFILE}.sha256" | cut -d ' ' -f 1)
-    CURRMD5=$(sha256sum "/storage/.update/${UFILE}" | cut -d ' ' -f 1)
-    if test "${DISTMD5}" = "${CURRMD5}"
-    then
-	echo "valid checksum."
-    else
-	echo "invalid checksum. Got +${DISTMD5}+. Attempted +${CURRMD5}+."
-	exit 1
-    fi
-else
-    echo "no checksum found. don't check the file."
-fi
-
-# a sync
-sync
-echo "Done. Please reboot EmuELEC so that the changes take effect!"
-exit 0
+echo "Done. Please reboot the system so changes take effect!"
